Components/CartSummaryViewComponent.cs
using System;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookstoreProject.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
        
    }
}

Components/TypesViewComponent.cs
using System;
using System.Linq;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookstoreProject.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreProjectRepository repo { get; set; }

        public TypesViewComponent (IBookstoreProjectRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookCategory"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">

    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("C", CultureInfo.CreateSpecificCulture("en-US"))</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">Isbn: @Model.Isbn</div>
    <div class="card-text p-1">Classification: @Model.Classification</div>
    <div class="card-text p-1">Category: @Model.Category</div>
    <div class="card-text p-1">PageCount: @Model.PageCount</div>

    <form method="post" asp-page="/Shop">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathandQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Buy</button>
        </span>

    </form>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/c5ab850438.js" crossorigin="anonymous"></script>
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">The Bookstore</div>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                    </div>
                        <vc:account></vc:account>
                        <a class="nav-link">Login</a>
                    <div>
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>
    <footer>THE END</footer>
</body>
</html>