Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BookstoreProject.Controllers
{
    public class PurchaseController : Controller
    {
        public IPurchaseRepository repo { get; set; }

        private Cart cart { get; set; }

        public PurchaseController (IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();
                return RedirectToPage("/PurchaseConfirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookstoreProject.Infrastructure;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookstoreProject.Pages
{
    public class ShopModel : PageModel
    {
        private IBookstoreProjectRepository repo { get; set; }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }


        public ShopModel (IBookstoreProjectRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl});
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new {ReturnUrl = returnUrl});
        }
    }
}

Pages/PurchaseConfirmation.cshtml
@page
@{
}

<div class="text-center">
    <h4>
        Thank you! your purchse will be processed shortly
    </h4>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Home</a>
</div>

Pages/Shop.cshtml
@page
@model BookstoreProject.Pages.ShopModel
@{
}
<h2>Your Cart</h2><br />

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var i in Model.cart.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>@i.Book.Price.ToString("C", CultureInfo.CreateSpecificCulture("en-US"))</td>
                    <td>@((i.Quantity * i.Book.Price).ToString("C", CultureInfo.CreateSpecificCulture("en-US")))</td>
                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="bookId" value="@i.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td >@Model.cart.CalculateTotal().ToString("C", CultureInfo.CreateSpecificCulture("en-US"))</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Return to Shopping</a>
    <a class="btn btn-primary" asp-controller="Purchase" asp-action="checkout">Checkout</a>
</div>

Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">The Old Bookstore</span>
    </div>

    <div class="row m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>